jobs:
  checks:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae
      name: run code checkers
      run: 'make install-notests

        '
  reproducible-build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae
      name: run first build
      run: 'make install-notests

        '
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae -Dbasepom.test.skip=true
      name: compare builds
      run: 'make compare-reproducible

        '
name: Run all code checkers (style, static analysis, api versions etc.)
on:
  repository_dispatch:
    types: trigger-ga___checkers.yml
