jobs:
  ci:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: build_jdk
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      id: test_jdk
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      env:
        JAVA_HOME: ${{ steps.build_jdk.outputs.path }}
      name: set build_jdk
      run: 'echo "$JAVA_HOME/bin" >> ${GITHUB_PATH}

        '
    - continue-on-error: true
      env:
        JAVA_HOME: ${{ steps.build_jdk.outputs.path }}
        MAVEN_CONFIG: -Dbasepom.check.skip-enforcer=false -B -fae
      name: build distribution
      run: 'make install-fast

        '
    - continue-on-error: true
      env:
        JAVA_HOME: ${{ steps.test_jdk.outputs.path }}
      name: set test_jdk
      run: 'echo "$JAVA_HOME/bin" >> ${GITHUB_PATH}

        '
    - continue-on-error: true
      env:
        JAVA_HOME: ${{ steps.test_jdk.outputs.path }}
        MAVEN_CONFIG: -B -fae
      name: run tests
      run: 'make run-tests

        '
    strategy:
      matrix:
        java-version:
        - 11
        - 17
        - 21
        - 22-ea
  ci-locale:
    name: Run tests with different timezone and locale
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae
      name: install code
      run: 'make install-fast

        '
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae -Djdbi.test.timezone=Asia/Colombo -Djdbi.test.language=tr
          -Djdbi.test.region=TR
      name: run tests
      run: 'make run-tests

        '
name: CI Build with tests
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
