jobs:
  doc:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -Dbasepom.check.fail-javadoc=true -B -fae
      name: docs
      run: 'make docs

        '
name: Documentation build
on:
  repository_dispatch:
    types: trigger-ga___doc.yml
