jobs:
  flyway:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae
      name: Build
      run: 'make install-fast

        '
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae -pl :jdbi3-testing -Ddep.flyway.version=${{ matrix.flyway-version
          }}
      name: test flyway versions
      run: 'make run-tests

        '
    strategy:
      matrix:
        flyway-version:
        - 7.15.0
        - 8.2.3
        - 8.5.13
        - 9.22.3
name: Test Flyway versions
on:
  repository_dispatch:
    types: trigger-ga___flyway-versions.yml
