jobs:
  slow-tests:
    name: Run slow tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae
      name: install code
      run: 'make install-fast

        '
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae -Ddep.testcontainers.version=${{ matrix.testcontainer-version
          }} -Djdbi.test.mysql-version=${{ matrix.mysql-version }}
      name: run slow tests
      run: 'make run-slow-tests

        '
    strategy:
      matrix:
        include:
        - mysql-version: mysql:8.0
          testcontainer-version: 1.18.3
        mysql-version:
        - mysql:latest
        testcontainer-version:
        - 1.19.4
  slow-tests-locale:
    name: Run slow tests with different timezone and locale
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae
      name: install code
      run: 'make install-fast

        '
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae -Djdbi.test.timezone=Asia/Colombo -Djdbi.test.language=tr
          -Djdbi.test.region=TR
      name: run slow tests
      run: 'make run-slow-tests

        '
name: Run all tests, including slow tests
on:
  repository_dispatch:
    types: trigger-ga___slow-tests.yml
