jobs:
  guava:
    name: Test Guava versions
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae
      name: Build
      run: 'make install-fast

        '
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae -pl :jdbi3-guava,:jdbi3-guice -Ddep.guava.version=${{
          matrix.test-version }}
      name: Test
      run: 'make run-tests

        '
    strategy:
      matrix:
        test-version:
        - 33.0.0-jre
        - 32.1.3-jre
        - 32.0.1-jre
        - 31.1-jre
  guice:
    name: Test guice versions
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae
      name: Build
      run: 'make install-fast

        '
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae -pl :jdbi3-guice -Ddep.guice.version=${{ matrix.test-version
          }}
      name: Test
      run: 'make run-tests

        '
    strategy:
      matrix:
        test-version:
        - 5.1.0
        - 6.0.0
        - 7.0.0
  immutables:
    name: Test Immutables versions
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae
      name: Build
      run: 'make install-fast

        '
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae -pl :jdbi3-core -Ddep.immutables.version=${{ matrix.test-version
          }}
      name: Test
      run: 'make run-tests

        '
    strategy:
      matrix:
        test-version:
        - 2.10.0
        - 2.9.3
        - 2.8.9-ea-1
  jackson2:
    name: Test Jackson Versions
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae
      name: Build
      run: 'make install-fast

        '
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae -pl :jdbi3-jackson2 -Ddep.jackson2.version=${{ matrix.test-version
          }}
      name: Test
      run: 'make run-tests

        '
    strategy:
      matrix:
        test-version:
        - 2.16.1
        - 2.15.3
        - 2.14.3
        - 2.13.5
        - 2.12.7.20221012
  jodatime2:
    name: Test joda-time versions
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae
      name: Build
      run: 'make install-fast

        '
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae -pl :jdbi3-jodatime2 -Ddep.joda-time.version=${{ matrix.test-version
          }}
      name: Test
      run: 'make run-tests

        '
    strategy:
      matrix:
        test-version:
        - 2.12.5
        - 2.11.2
        - 2.10.14
        - 2.9.9
  kotlin:
    name: Test kotlin runtime versions
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae
      name: Build
      run: 'make install-fast

        '
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae -pl :jdbi3-kotlin,:jdbi3-kotlin-sqlobject -Ddep.kotlin.version=${{
          matrix.test-version }}
      name: Test
      run: 'make run-tests

        '
    strategy:
      matrix:
        test-version:
        - 1.6.21
        - 1.7.21
        - 1.8.22
        - 1.9.22
  spring:
    name: Test spring framework versions
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae
      name: Build
      run: 'make install-fast

        '
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae -pl :jdbi3-spring5 -Ddep.spring.version=${{ matrix.test-version
          }}
      name: Test
      run: 'make run-tests

        '
    strategy:
      matrix:
        test-version:
        - 5.3.31
        - 6.0.15
        - 6.1.2
  vavr:
    name: Test vavr versions
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae
      name: Build
      run: 'make install-fast

        '
    - continue-on-error: true
      env:
        MAVEN_CONFIG: -B -fae -pl :jdbi3-vavr -Ddep.vavr.version=${{ matrix.test-version
          }}
      name: Test
      run: 'make run-tests

        '
    strategy:
      matrix:
        test-version:
        - 0.10.4
name: Test dependency versions
on:
  repository_dispatch:
    types: trigger-ga___versions-check.yml
